### ISSUE TITLE
subch network

### ISSUE THREAD

**Issue by sandshrews** [starkiller-astro/Microphysics#152] opened 2018-09-11 14:24 UTC
When trying to run `unit_test/burn_cell/` for the `inputs_burn_subch.VODE` file using the subch network, throws the error:

`At line 122 of file ../../networks/subch/actual_network.F90
Fortran runtime error: Attempting to allocate already allocated variable 'aion'`

This was not an issue with the URCA Simple network.

**Comment by zingale** [comment] 2018-09-11 14:44
The issue is that for subch, `actual_burner_init()` calls `actual_network_init()` while for URCA-simple, it does not.

So for subch, we are doing that init twice.  

@dwillcox do you have thoughts on where it should be?

**Comment by zingale** [comment] 2018-09-11 15:09
actually, this seems to be a new thing in the pynucastro template.  It looks like the most nets don't call actual_network_init from actual_burner.  I'm going to change them, and we should modify pynucastro

**Comment by zingale** [comment] 2018-09-11 15:11
this should be fixed now

**Closed** 2018-09-28 21:41 UTC
