### ISSUE TITLE
allow single precision

### ISSUE THREAD

**Issue by zingale** [starkiller-astro/Microphysics#218] opened 2019-11-21 01:12 UTC
At the moment, there are a lot of constants that use the `d` precision specifier instead of `_rt`, and a lot of declarations that use `double precision` instead of `real(rt)`.  We should switch everything over to `rt` so we can choose the precision at compile time.  This will let us do single precision on GPUs.

**Comment by maxpkatz** [comment] 2019-11-28 19:00
This is a duplicate of #193

**Closed by maxpkatz** 2019-11-28 19:00 UTC
